# frozen_string_literal: true

namespace :content_strategy do
  desc 'Schedule next post using content strategy with AI caption generation'
  task schedule_next: :environment do
    puts '🚀 Starting content strategy scheduling with caption generation...'

    # Find persona
    persona_name = ENV['PERSONA'] || 'sarah'
    persona = Persona.find_by(name: persona_name)
    
    unless persona
      puts "❌ Error: Persona '#{persona_name}' not found"
      puts "Available personas: #{Persona.pluck(:name).join(', ')}"
      exit 1
    end
    
    puts "✓ Found persona: #{persona.name}"

    # Check caption config
    if persona.caption_config.present?
      puts "✓ Caption config found (tone: #{persona.caption_config.tone})"
    else
      puts "⚠ No caption config - will use fallback captions"
    end

    # Prepare post content using strategy
    strategy_name = ENV['STRATEGY'] || nil
    generate_caption = ENV['GENERATE_CAPTION'] != 'false'
    
    puts "\n📋 Preparing post content..."
    puts "   Strategy: #{strategy_name || 'default'}"
    puts "   Generate Caption: #{generate_caption}"
    
    begin
      result = ContentStrategy::PreparePostContent.new(
        persona: persona,
        strategy_name: strategy_name,
        generate_caption: generate_caption
      ).call

      unless result[:success]
        puts "❌ Failed to prepare content: #{result[:error]}"
        exit 1
      end

      # Display selected content
      puts "\n✅ Content prepared successfully!"
      puts "   Photo: #{result[:photo].path}"
      puts "   Cluster: #{result[:cluster]&.name || 'None'}"
      puts "   Strategy: #{result[:strategy_name]}"
      puts "   Format: #{result[:format]}"
      puts "   Optimal Time: #{result[:optimal_time]}"
      puts "\n   Caption (#{result[:caption].length} chars):"
      puts "   " + "─" * 60
      puts "   #{result[:caption]}"
      puts "   " + "─" * 60
      
      if result[:caption_metadata]
        puts "\n   Caption Metadata:"
        puts "     Generated by: #{result[:caption_metadata][:generated_by]}"
        puts "     Quality score: #{result[:caption_metadata][:quality_score]}" if result[:caption_metadata][:quality_score]
        puts "     Model: #{result[:caption_metadata][:model]}" if result[:caption_metadata][:model]
      end

      # Ensure photo has attachment
      photo = result[:photo]
      unless photo.image.attached?
        puts "\n📎 Attaching image to photo record..."
        photo.image.attach(io: File.open(photo.path), filename: File.basename(photo.path))
      end

      # Schedule the post
      puts "\n📤 Scheduling post to Instagram..."
      
      schedule_result = Scheduling.schedule_post(
        photo: photo,
        persona: persona,
        caption: result[:caption],
        caption_metadata: result[:caption_metadata] || {}
      )

      if schedule_result.success?
        puts "\n✅ Post scheduled successfully!"
        puts "   Instagram Post ID: #{schedule_result.post.provider_post_id}"
        puts "   Status: #{schedule_result.post.status}"
      else
        puts "\n❌ Failed to schedule post"
        puts "   Errors: #{schedule_result.errors.full_messages.join(', ')}"
        exit 1
      end

    rescue ContentStrategy::NoAvailableClustersError => e
      puts "\n❌ No available clusters for posting"
      puts "   #{e.message}"
      exit 1
    rescue ContentStrategy::NoUnpostedPhotosError => e
      puts "\n❌ No unposted photos available"
      puts "   #{e.message}"
      exit 1
    rescue StandardError => e
      puts "\n❌ Unexpected error: #{e.message}"
      puts e.backtrace.first(5).join("\n")
      exit 1
    end
  end

  desc 'Preview next post content without scheduling'
  task preview_next: :environment do
    puts '👀 Previewing next post content...'

    persona_name = ENV['PERSONA'] || 'sarah'
    persona = Persona.find_by(name: persona_name)
    
    unless persona
      puts "❌ Error: Persona '#{persona_name}' not found"
      exit 1
    end

    puts "✓ Persona: #{persona.name}"

    result = ContentStrategy::PreparePostContent.new(
      persona: persona,
      generate_caption: true
    ).call

    if result[:success]
      puts "\n📸 Selected Photo: #{result[:photo].path}"
      puts "🏷️  Cluster: #{result[:cluster]&.name || 'None'}"
      puts "📋 Strategy: #{result[:strategy_name]}"
      puts "⏰ Optimal Time: #{result[:optimal_time]}"
      puts "\n💬 Caption (#{result[:caption].length} chars):"
      puts "─" * 70
      puts result[:caption]
      puts "─" * 70
      
      if result[:caption_metadata]
        puts "\n📊 Metadata:"
        result[:caption_metadata].each do |key, value|
          puts "   #{key}: #{value}"
        end
      end
    else
      puts "❌ Failed: #{result[:error]}"
    end
  end
end
