# Example credentials structure for ActiveStorage B2 configuration
# Use `bin/rails credentials:edit` to add these values to config/credentials.yml.enc
#
# b2:
#   access_key_id: your_b2_access_key_id_here
#   application_key: your_b2_application_key_here
#
# The actual values should be obtained from your Backblaze B2 account
# and added securely via the Rails credentials system.
#
# IMPORTANT: Configure your B2 bucket for public read access to ensure
# that the Buffer API can download photos from the generated URLs.