# Test intelligent hashtag generation for Thanksgiving photo

photo = Photo.find(24727)
sarah = Persona.find_by!(name: 'sarah')
cluster = photo.cluster

puts "🎨 Testing Intelligent Hashtag Generation"
puts "=" * 60
puts "Photo ID: #{photo.id}"
puts "Cluster: #{cluster&.name}"
puts ""

# Generate hashtags using intelligent system
result = HashtagGenerations::Generator.generate(
  photo: photo,
  persona: sarah,
  cluster: cluster,
  count: 10
)

puts "✨ Generated Hashtags:"
result[:hashtags].each_with_index do |tag, i|
  puts "   #{i+1}. #{tag}"
end

puts ""
puts "📊 Metadata:"
puts "   Method: #{result[:metadata][:method]}"
puts "   Generated by: #{result[:metadata][:generated_by]}"
puts "   Content tags: #{result[:metadata][:content_tags_count]}"
puts "   Total candidates: #{result[:metadata][:total_candidates]}"
puts "   Selected: #{result[:metadata][:selected_count]}"

puts ""
puts "🎯 These hashtags are:"
puts "   ✅ Content-specific (based on photo analysis)"
puts "   ✅ Persona-aligned (matches Sarah's niche)"
puts "   ✅ Optimally mixed (large/medium/niche balance)"
puts "   ✅ Thanksgiving-appropriate"
